# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/videoSystem.xdc

# Block Designs: bd/vgaSystem/vgaSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem || ORIG_REF_NAME==vgaSystem} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_clk_wiz_0_0/vgaSystem_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_clk_wiz_0_0 || ORIG_REF_NAME==vgaSystem_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_v_axi4s_vid_out_0_0/vgaSystem_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vgaSystem_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_v_tc_0_0/vgaSystem_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_v_tc_0_0 || ORIG_REF_NAME==vgaSystem_v_tc_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_rst_clk_wiz_0_148M_0/vgaSystem_rst_clk_wiz_0_148M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_rst_clk_wiz_0_148M_0 || ORIG_REF_NAME==vgaSystem_rst_clk_wiz_0_148M_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_xlconstant_0_0/vgaSystem_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_xlconstant_0_0 || ORIG_REF_NAME==vgaSystem_xlconstant_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_xlslice_0_0/vgaSystem_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_xlslice_0_0 || ORIG_REF_NAME==vgaSystem_xlslice_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_xlslice_0_1/vgaSystem_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_xlslice_0_1 || ORIG_REF_NAME==vgaSystem_xlslice_0_1} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_xlslice_1_0/vgaSystem_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_xlslice_1_0 || ORIG_REF_NAME==vgaSystem_xlslice_1_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_mux_0_0/vgaSystem_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_mux_0_0 || ORIG_REF_NAME==vgaSystem_mux_0_0} -quiet] -quiet

# IP: bd/vgaSystem/ip/vgaSystem_dataGen_0_0/vgaSystem_dataGen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgaSystem_dataGen_0_0 || ORIG_REF_NAME==vgaSystem_dataGen_0_0} -quiet] -quiet

# XDC: c:/GitHub/EmbeddedVGA_Zynq/vgainterface.gen/sources_1/bd/vgaSystem/vgaSystem_ooc.xdc
